# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/VivadoWS/mini_prj/mini_prj.srcs/sources_1/ip/x_bram_3/x_bram_3.xci
# IP: The module: 'x_bram_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoWS/mini_prj/mini_prj.gen/sources_1/ip/x_bram_3/x_bram_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'x_bram_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/VivadoWS/mini_prj/mini_prj.srcs/sources_1/ip/x_bram_3/x_bram_3.xci
# IP: The module: 'x_bram_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoWS/mini_prj/mini_prj.gen/sources_1/ip/x_bram_3/x_bram_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'x_bram_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
