# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/VivadoWS/mini_prj/mini_prj.srcs/sources_1/ip/w_bram_5/w_bram_5.xci
# IP: The module: 'w_bram_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoWS/mini_prj/mini_prj.gen/sources_1/ip/w_bram_5/w_bram_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'w_bram_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/VivadoWS/mini_prj/mini_prj.srcs/sources_1/ip/w_bram_5/w_bram_5.xci
# IP: The module: 'w_bram_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoWS/mini_prj/mini_prj.gen/sources_1/ip/w_bram_5/w_bram_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'w_bram_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
